/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as NewAttemptRouteImport } from './routes/new-attempt'
import { Route as HealthCheckRouteImport } from './routes/health-check'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems.$problemId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAttemptRoute = NewAttemptRouteImport.update({
  id: '/new-attempt',
  path: '/new-attempt',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthCheckRoute = HealthCheckRouteImport.update({
  id: '/health-check',
  path: '/health-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/problems/$problemId',
  path: '/problems/$problemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/health-check': typeof HealthCheckRoute
  '/new-attempt': typeof NewAttemptRoute
  '/stats': typeof StatsRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/health-check': typeof HealthCheckRoute
  '/new-attempt': typeof NewAttemptRoute
  '/stats': typeof StatsRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems': typeof ProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/health-check': typeof HealthCheckRoute
  '/new-attempt': typeof NewAttemptRoute
  '/stats': typeof StatsRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/health-check'
    | '/new-attempt'
    | '/stats'
    | '/problems/$problemId'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/health-check'
    | '/new-attempt'
    | '/stats'
    | '/problems/$problemId'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/health-check'
    | '/new-attempt'
    | '/stats'
    | '/problems/$problemId'
    | '/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HealthCheckRoute: typeof HealthCheckRoute
  NewAttemptRoute: typeof NewAttemptRoute
  StatsRoute: typeof StatsRoute
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-attempt': {
      id: '/new-attempt'
      path: '/new-attempt'
      fullPath: '/new-attempt'
      preLoaderRoute: typeof NewAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-check': {
      id: '/health-check'
      path: '/health-check'
      fullPath: '/health-check'
      preLoaderRoute: typeof HealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/problems/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HealthCheckRoute: HealthCheckRoute,
  NewAttemptRoute: NewAttemptRoute,
  StatsRoute: StatsRoute,
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
